/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelingsaleman_trab1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.net.URL;
import java.text.DecimalFormat;

/**
 *
 * @author Otavio Tarelho | Mariana Bispo | Leonardo de Oliveira
 * 
 */

public class Caixeiro extends javax.swing.JFrame {

    /**
     * Creates new form Caixeiro
     */
    public Caixeiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _citymap = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _log = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _generations = new javax.swing.JFormattedTextField();
        _population = new javax.swing.JFormattedTextField();
        _mutation = new javax.swing.JFormattedTextField();
        Gerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        _citymap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cidade Mapa 1", "Cidade Mapa 2", "Cidade Mapa 3", "Cidade Mapa 4", "Cidade Mapa 5", "Cidade Mapa 6" }));

        jLabel1.setText("Gerações");

        _log.setColumns(20);
        _log.setRows(5);
        jScrollPane1.setViewportView(_log);

        jLabel2.setText("População");

        jLabel3.setText("Prob. Mutação");

        _generations.setColumns(5);
        _generations.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        _generations.setText("1000");

        _population.setColumns(5);
        _population.setText("300");

        _mutation.setColumns(5);
        _mutation.setText("0.015");

        Gerar.setText("Gerar Solução");
        Gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_citymap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_generations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_population, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_mutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(Gerar)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_citymap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(_generations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_population, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_mutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gerar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarActionPerformed
        
        if(!CityManager.isEmpty()){
            CityManager.remove();
        }
        
        _log.removeAll();
        
        int c = _citymap.getSelectedIndex();
        String FILE_NAME = "cidades_mapa"+(c+1)+".txt";
        try {
           URL path = this.getClass().getResource(FILE_NAME);
           File FILE = new File(path.toURI());
           BufferedReader READ = new BufferedReader(new FileReader(FILE)); 
           String line = READ.readLine();
           while(line != null){
               String[] splited = line.split(";");
               City city = new City(Integer.valueOf(splited[0]), 
                       Double.valueOf(splited[1]), Double.valueOf(splited[2]));
               CityManager.add(city);
               
               line = READ.readLine();
           } 
        } catch(Exception e){
            e.printStackTrace();
        }
        
        int genSize = Integer.valueOf(_generations.getText());
        int popSize = Integer.valueOf(_population.getText());
        double mutation = Double.valueOf(_mutation.getText());
        DecimalFormat df = new DecimalFormat("0.0000000"); 
        
        GeneticAlg.setMutation(mutation);
        
        Population pop = new Population(popSize, true);
        
        _log.append("Distância Inicial: " + pop.getFittest().getDistance() + "\n\n");
        Route best_route = new Route();
        int best_generation = 0;
        int best_distance = Integer.MAX_VALUE;
        
        for (int i = 1; i <= genSize; i++) {
            _log.append("Geração " + i + "\nPonto do Melhor Adaptado: " + df.format(pop.getFittest().getFitness()));
            _log.append("\nDistância do Percurso: " + pop.getFittest().getDistance());
            
            if(pop.getFittest().getDistance() < best_distance){
                best_distance = pop.getFittest().getDistance();
                best_route = pop.getFittest();
                best_generation = i;
            }
            
            _log.append("\nRota: \n");
            _log.append(pop.getFittest().toString());
            _log.append("\n");
            
            pop = GeneticAlg.evolve(pop);
            
        }
        
        _log.append("Melhor Distância: " + best_distance + "\n");
        _log.append("Melhor Geração: " + best_generation + "\n");
        _log.append("Melhor Rota: \n" + best_route.toString() + "\n");
    }//GEN-LAST:event_GerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gerar;
    private javax.swing.JComboBox<String> _citymap;
    private javax.swing.JFormattedTextField _generations;
    private javax.swing.JTextArea _log;
    private javax.swing.JFormattedTextField _mutation;
    private javax.swing.JFormattedTextField _population;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
